project:
  type: website

website:
  title: "Bite-sized Library workshops"
  navbar:
    left: 
      - text: "R Series"
        menu: 
          - text: "Episode 1"
            href: Episode1.html
      - text: "Now Your See It!"
        href: introTableau.html
      - text: "Introduction to QGIS"
        href: introQGIS.html
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

